using System.Diagnostics; using System.Net; using System.Net.NetworkInformation; using System.Net.Sockets; using EthernetLinkTester.Models;
namespace EthernetLinkTester.Services;
public sealed class IpTestService {
 public async Task<(double min,double avg,double max,double jitter,double loss)> PingStats(string host,int count=30,int timeout=1200){using var p=new Ping();var a=new List<double>();int lost=0;for(int i=0;i<count;i++){try{var r=await p.SendPingAsync(host,timeout);if(r.Status==IPStatus.Success)a.Add(r.RoundtripTime);else lost++;}catch{lost++;}await Task.Delay(40);}var d=a.Zip(a.Skip(1),(x,y)=>Math.Abs(y-x)).ToArray();return(a.Count==0?0:a.Min(),a.Count==0?0:a.Average(),a.Count==0?0:a.Max(),d.Length==0?0:d.Average(),100.0*lost/count);}
 public async Task<double> TcpThroughput(string host,int port,TimeSpan duration,CancellationToken ct=default){using var c=new TcpClient();await c.ConnectAsync(host,port,ct);c.NoDelay=true;var s=c.GetStream();var b=new byte[1024*1024];Random.Shared.NextBytes(b);long n=0;var sw=Stopwatch.StartNew();while(sw.Elapsed<duration&&!ct.IsCancellationRequested){await s.WriteAsync(b,ct);n+=b.Length;}await s.FlushAsync(ct);return n*8/sw.Elapsed.TotalSeconds/1e6;}
 public async Task<(double mbps,double loss,double jitter)> UdpEcho(string host,int port,double offeredMbps,TimeSpan duration,int payload=1200,CancellationToken ct=default){using var u=new UdpClient();u.Connect(host,port);var b=new byte[Math.Max(64,payload)];b[0]=0x45;b[1]=0x4C;b[2]=0x54;b[3]=1;long sent=0,recv=0;var arrivals=new List<double>();var sw=Stopwatch.StartNew();long seq=0;double pps=Math.Max(1,offeredMbps*1e6/(b.Length*8.0));var delay=TimeSpan.FromSeconds(1/pps);while(sw.Elapsed<duration&&!ct.IsCancellationRequested){BitConverter.GetBytes(seq++).CopyTo(b,4);BitConverter.GetBytes(Stopwatch.GetTimestamp()).CopyTo(b,12);await u.SendAsync(b,ct);sent++;try{using var t=new CancellationTokenSource(100);using var linked=CancellationTokenSource.CreateLinkedTokenSource(ct,t.Token);var r=await u.ReceiveAsync(linked.Token);recv++;arrivals.Add(sw.Elapsed.TotalMilliseconds);}catch{} if(delay.TotalMilliseconds>=1)await Task.Delay(delay,ct);}var dif=arrivals.Zip(arrivals.Skip(1),(x,y)=>Math.Abs(y-x)).ToArray();return(sent*b.Length*8/sw.Elapsed.TotalSeconds/1e6, sent==0?0:100.0*(sent-recv)/sent,dif.Length==0?0:dif.Average());}
 public async Task<int> DetectMtu(string host,int min=576,int max=9000){using var p=new Ping();while(min<max){int mid=(min+max+1)/2;int payload=Math.Max(0,mid-28);try{var r=await p.SendPingAsync(host,800,new byte[payload],new PingOptions(64,true));if(r.Status==IPStatus.Success)min=mid;else max=mid-1;}catch{max=mid-1;}}return min;}
 public async Task<List<PortResult>> ScanPorts(string host,IEnumerable<int> ports){var list=new List<PortResult>();foreach(var port in ports){var sw=Stopwatch.StartNew();string st="FERMÉ/TIMEOUT";try{using var c=new TcpClient();using var x=new CancellationTokenSource(600);await c.ConnectAsync(host,port,x.Token);st="OUVERT";}catch{}sw.Stop();list.Add(new(port,"TCP",st,sw.Elapsed.TotalMilliseconds));
 var usw=Stopwatch.StartNew();string ust="INDÉTERMINÉ";try{using var u=new UdpClient();u.Connect(host,port);var b=new byte[64];b[0]=0x45;b[1]=0x4C;b[2]=0x54;b[3]=1;await u.SendAsync(b);using var x=new CancellationTokenSource(500);var r=await u.ReceiveAsync(x.Token);ust=r.Buffer.Length>3&&r.Buffer[0]==0x45?"OUVERT/RÉPONSE":"RÉPONSE";}catch(SocketException){ust="FERMÉ/ICMP";}catch{}usw.Stop();list.Add(new(port,"UDP",ust,usw.Elapsed.TotalMilliseconds));}return list;}
}
