using SharpPcap; using EthernetLinkTester.Models;
namespace EthernetLinkTester.Services;
public sealed class Layer2Service : IDisposable {
 ICaptureDevice? reflector; Action<string>? reflLog;
 public IReadOnlyList<string> Adapters(){try{return CaptureDeviceList.Instance.Select(d=>d.Name+" | "+d.Description).ToList();}catch{return Array.Empty<string>();}}
 static ICaptureDevice Find(string token){var d=CaptureDeviceList.Instance.FirstOrDefault(x=>x.Name==token|| (x.Name+" | "+x.Description)==token);return d??throw new InvalidOperationException("Interface Npcap introuvable. Installez Npcap et relancez l'application.");}
 public void StartReflector(string adapter,Action<string> log){StopReflector();reflector=Find(adapter);reflLog=log;reflector.OnPacketArrival+=Reflect;reflector.Open(DeviceModes.Promiscuous,500);reflector.StartCapture();log("Réflecteur Ethernet L2/VLAN actif via Npcap.");}
 void Reflect(object sender,PacketCapture e){try{var raw=e.GetPacket().Data;if(raw.Length<28)return;int off=(raw[12]==0x88&&raw[13]==0xA8&&raw.Length>22&&raw[16]==0x81&&raw[17]==0x00)?22:((raw[12]==0x81&&raw[13]==0x00)?18:14);if(raw.Length<off+8)return;if(raw[off]!=0x45||raw[off+1]!=0x4C||raw[off+2]!=0x54||raw[off+3]!=0x32)return;var reply=(byte[])raw.Clone();for(int i=0;i<6;i++){(reply[i],reply[i+6])=(reply[i+6],reply[i]);}reply[off+4]=2;reflector?.SendPacket(reply);}catch(Exception ex){reflLog?.Invoke("L2 reflector: "+ex.Message);} }
 public void StopReflector(){try{if(reflector!=null){reflector.StopCapture();reflector.OnPacketArrival-=Reflect;}}catch{}reflector=null;}
 public async Task<VlanResult> TestVlan(string adapter,string srcMac,string dstMac,int vid,int pcp,int count=20,int timeoutMs=600){var d=Find(adapter);var src=Mac(srcMac);var dst=Mac(dstMac);int recv=0;int? rvid=null;var tcs=new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);void H(object s,PacketCapture e){var a=e.GetPacket().Data;if(a.Length<30)return;int o=(a[12]==0x81&&a[13]==0x00)?18:14;if(a[o]==0x45&&a[o+1]==0x4C&&a[o+2]==0x54&&a[o+3]==0x32&&a[o+4]==2){recv++;if(a[12]==0x81&&a[13]==0x00)rvid=((a[14]&0x0F)<<8)|a[15];if(recv>=count)tcs.TrySetResult(true);}}
 d.OnPacketArrival+=H;d.Open(DeviceModes.Promiscuous,300);d.StartCapture();try{for(int i=0;i<count;i++){d.SendPacket(Frame(src,dst,vid,pcp,i));await Task.Delay(15);}await Task.WhenAny(tcs.Task,Task.Delay(timeoutMs));}finally{try{d.StopCapture();}catch{}d.OnPacketArrival-=H;}double loss=100.0*(count-recv)/count;string st=recv==0?"FAIL":(rvid==vid?"PASS":"MODIFIÉ");return new(vid,rvid,pcp,st,count,recv,loss,rvid is null?"Aucune réponse L2":$"VLAN reçu {rvid}");}
 public async Task<List<VlanResult>> ScanVlans(string adapter,string srcMac,string dstMac,int from,int to,int pcp,IProgress<int>? progress=null){var l=new List<VlanResult>();int total=Math.Max(1,to-from+1);for(int v=from;v<=to;v++){l.Add(await TestVlan(adapter,srcMac,dstMac,v,pcp,3,220));progress?.Report((v-from+1)*100/total);}return l;}
 static byte[] Frame(byte[] src,byte[] dst,int vid,int pcp,int seq){var b=new byte[64];Buffer.BlockCopy(dst,0,b,0,6);Buffer.BlockCopy(src,0,b,6,6);b[12]=0x81;b[13]=0x00;ushort tci=(ushort)(((pcp&7)<<13)|(vid&0xFFF));b[14]=(byte)(tci>>8);b[15]=(byte)tci;b[16]=0x88;b[17]=0xB5;b[18]=0x45;b[19]=0x4C;b[20]=0x54;b[21]=0x32;b[22]=1;BitConverter.GetBytes(seq).CopyTo(b,23);BitConverter.GetBytes(DateTime.UtcNow.Ticks).CopyTo(b,27);return b;}
 public async Task<VlanResult> TestQinQ(string adapter,string srcMac,string dstMac,int outerVid,int innerVid,int pcp,int count=20,int timeoutMs=600){var d=Find(adapter);var src=Mac(srcMac);var dst=Mac(dstMac);int recv=0;var tcs=new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);void H(object s,PacketCapture e){var a=e.GetPacket().Data;if(a.Length<34)return;int o=(a[12]==0x88&&a[13]==0xA8&&a[16]==0x81&&a[17]==0x00)?22:-1;if(o>0&&a[o]==0x45&&a[o+1]==0x4C&&a[o+2]==0x54&&a[o+3]==0x32&&a[o+4]==2){recv++;if(recv>=count)tcs.TrySetResult(true);}}d.OnPacketArrival+=H;d.Open(DeviceModes.Promiscuous,300);d.StartCapture();try{for(int i=0;i<count;i++){d.SendPacket(QinQFrame(src,dst,outerVid,innerVid,pcp,i));await Task.Delay(15);}await Task.WhenAny(tcs.Task,Task.Delay(timeoutMs));}finally{try{d.StopCapture();}catch{}d.OnPacketArrival-=H;}double loss=100.0*(count-recv)/count;return new(innerVid,innerVid,pcp,recv>0?"PASS":"FAIL",count,recv,loss,$"QinQ S-VLAN {outerVid} / C-VLAN {innerVid}");}
 static byte[] QinQFrame(byte[] src,byte[] dst,int outer,int inner,int pcp,int seq){var b=new byte[68];Buffer.BlockCopy(dst,0,b,0,6);Buffer.BlockCopy(src,0,b,6,6);b[12]=0x88;b[13]=0xA8;ushort o=(ushort)(((pcp&7)<<13)|(outer&0xFFF));b[14]=(byte)(o>>8);b[15]=(byte)o;b[16]=0x81;b[17]=0x00;ushort inn=(ushort)(inner&0xFFF);b[18]=(byte)(inn>>8);b[19]=(byte)inn;b[20]=0x88;b[21]=0xB5;b[22]=0x45;b[23]=0x4C;b[24]=0x54;b[25]=0x32;b[26]=1;BitConverter.GetBytes(seq).CopyTo(b,27);return b;}
 static byte[] Mac(string s){var p=s.Replace("-",":").Split(':');if(p.Length!=6)throw new FormatException("MAC attendue: AA:BB:CC:DD:EE:FF");return p.Select(x=>Convert.ToByte(x,16)).ToArray();}
 public void Dispose()=>StopReflector();
}
