using System.Collections.ObjectModel; using System.Windows; using EthernetLinkTester.Models; using EthernetLinkTester.Services;
namespace EthernetLinkTester;
public partial class MainWindow:Window{
 readonly IpTestService ip=new(); readonly ReceiverHost rx=new(); readonly Layer2Service l2=new(); readonly ReportService report=new();
 readonly ObservableCollection<PortResult> ports=new(); readonly ObservableCollection<VlanResult> vlans=new(); readonly ObservableCollection<Rfc2544Row> rfc=new(); readonly ObservableCollection<Y1564Service> yservices=new(); readonly ObservableCollection<Y1564Result> yresults=new(); readonly ObservableCollection<HistoryRow> history=new(); bool receiver;
 int Port=>int.TryParse(PortBox.Text,out var p)?p:5201; string Host=>RemoteIp.Text.Trim(); string OutDir=>System.IO.Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),"EthernetLinkTester","Reports");
 public MainWindow(){InitializeComponent();PortsGrid.ItemsSource=ports;VlanGrid.ItemsSource=vlans;RfcGrid.ItemsSource=rfc;YServicesGrid.ItemsSource=yservices;YResultGrid.ItemsSource=yresults;HistoryGrid.ItemsSource=history;RefreshAdapters();Log("Application prête. Sélectionnez le rôle du PC.");}
 void Log(string s)=>Dispatcher.Invoke(()=>{LogBox.AppendText($"[{DateTime.Now:HH:mm:ss}] {s}\n");LogBox.ScrollToEnd();}); void Hist(string t,string sum,string st="OK")=>Dispatcher.Invoke(()=>history.Insert(0,new(DateTime.Now,t,Host,sum,st)));
 async void Emitter_Click(object s,RoutedEventArgs e){rx.Stop();l2.StopReflector();receiver=false;RoleState.Text="● ÉMETTEUR / PILOTE";EmitterButton.Style=(Style)FindResource("PrimaryButton");ReceiverButton.ClearValue(StyleProperty);Log("Rôle : ÉMETTEUR. Les campagnes peuvent être lancées.");await Task.CompletedTask;}
 async void Receiver_Click(object s,RoutedEventArgs e){receiver=true;await rx.StartAsync(Port,Log);RoleState.Text="● RÉCEPTEUR TCP/UDP ACTIF";ReceiverButton.Style=(Style)FindResource("PrimaryButton");EmitterButton.ClearValue(StyleProperty);if(AdapterBox.SelectedItem is string a)try{l2.StartReflector(a,Log);RoleState.Text="● RÉCEPTEUR IP + L2 ACTIF";}catch(Exception ex){Log("Npcap/L2 non actif : "+ex.Message);}Log("Rôle : RÉCEPTEUR / REFLECTOR.");}
 bool Guard(){if(receiver){Log("Ce PC est Récepteur. Passez en Émetteur pour lancer une campagne.");return false;}return true;}
 async Task PingRun(){if(!Guard())return;Log("Mesure latence/gigue/pertes...");try{var p=await ip.PingStats(Host);LatencyText.Text=$"{p.avg:F2} ms";LatencySub.Text=$"{p.min:F1} / {p.avg:F1} / {p.max:F1}";JitterText.Text=$"{p.jitter:F2} ms";LossText.Text=$"{p.loss:F3} %";Hist("Latence",$"avg {p.avg:F2} ms, gigue {p.jitter:F2}, pertes {p.loss:F3}%");Log($"RTT {p.avg:F2} ms · gigue {p.jitter:F2} · perte {p.loss:F3}%");}catch(Exception ex){Log("Erreur ping: "+ex.Message);Hist("Latence",ex.Message,"FAIL");}}
 async Task TcpRun(){if(!Guard())return;try{Log("Débit TCP 10 secondes...");var m=await ip.TcpThroughput(Host,Port,TimeSpan.FromSeconds(10));TcpText.Text=$"{m:F1} Mbps";Hist("TCP",$"{m:F1} Mbit/s");Log($"TCP {m:F1} Mbit/s");}catch(Exception ex){Log("TCP: "+ex.Message+" — vérifiez le Récepteur.");Hist("TCP",ex.Message,"FAIL");}}
 async Task UdpRun(){if(!Guard())return;try{Log("UDP echo 10 secondes @ 100 Mbit/s...");var u=await ip.UdpEcho(Host,Port,100,TimeSpan.FromSeconds(10));Hist("UDP",$"{u.mbps:F1} Mbit/s, perte {u.loss:F3}%, gigue {u.jitter:F2}ms",u.loss<1?"PASS":"WARN");Log($"UDP offert {u.mbps:F1} Mbit/s · perte {u.loss:F3}% · gigue {u.jitter:F2}ms");}catch(Exception ex){Log("UDP: "+ex.Message);}}
 async void QuickPing_Click(object s,RoutedEventArgs e)=>await PingRun(); async void QuickTcp_Click(object s,RoutedEventArgs e)=>await TcpRun(); async void QuickUdp_Click(object s,RoutedEventArgs e)=>await UdpRun();
 async void AllQuick_Click(object s,RoutedEventArgs e){await PingRun();await TcpRun();await UdpRun();await MtuRun();}
 async Task MtuRun(){if(!Guard())return;try{Log("Détection MTU (DF)...");var m=await ip.DetectMtu(Host);MtuText.Text=$"MTU : {m} octets";Hist("MTU",m.ToString(),m>=1500?"PASS":"WARN");Log($"MTU IP maximale détectée: {m}");}catch(Exception ex){Log("MTU: "+ex.Message);}}
 async void Mtu_Click(object s,RoutedEventArgs e)=>await MtuRun();
 async void Ports_Click(object s,RoutedEventArgs e){if(!Guard())return;ports.Clear();var ps=PortsBox.Text.Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>int.TryParse(x.Trim(),out var p)?p:-1).Where(x=>x>0&&x<65536).Distinct();Log("Scan TCP...");foreach(var x in await ip.ScanPorts(Host,ps))ports.Add(x);Hist("Ports",$"{ports.Count} ports testés");}
 void RefreshAdapters(){AdapterBox.ItemsSource=l2.Adapters();if(AdapterBox.Items.Count>0)AdapterBox.SelectedIndex=0;} void RefreshAdapters_Click(object s,RoutedEventArgs e){RefreshAdapters();Log($"{AdapterBox.Items.Count} interface(s) Npcap détectée(s).");}
 async void VlanOne_Click(object s,RoutedEventArgs e){if(!Guard())return;if(AdapterBox.SelectedItem is not string a){Log("Aucune interface Npcap.");return;}try{int v=int.Parse(VlanId.Text),p=int.Parse(PcpBox.Text);var r=await l2.TestVlan(a,SrcMac.Text,DstMac.Text,v,p);vlans.Insert(0,r);Hist("VLAN",$"VID {v} => {r.Status}, reçu {r.ReceivedVid}",r.Status);Log($"VLAN {v}: {r.Status}, reçu {r.Received}/{r.Sent}");}catch(Exception ex){Log("VLAN: "+ex.Message);}}
 async void QinQ_Click(object s,RoutedEventArgs e){if(!Guard())return;if(AdapterBox.SelectedItem is not string a){Log("Aucune interface Npcap.");return;}try{int o=int.Parse(OuterVlan.Text),i=int.Parse(InnerVlan.Text),p=int.Parse(PcpBox.Text);var r=await l2.TestQinQ(a,SrcMac.Text,DstMac.Text,o,i,p);vlans.Insert(0,r);Hist("QinQ",$"S-VLAN {o}, C-VLAN {i}: {r.Status}",r.Status);Log($"QinQ {o}/{i}: {r.Status}");}catch(Exception ex){Log("QinQ: "+ex.Message);}}
 async void VlanScan_Click(object s,RoutedEventArgs e){if(!Guard())return;if(AdapterBox.SelectedItem is not string a){Log("Aucune interface Npcap.");return;}try{vlans.Clear();int f=int.Parse(VlanFrom.Text),t=int.Parse(VlanTo.Text),p=int.Parse(PcpBox.Text);f=Math.Clamp(f,1,4094);t=Math.Clamp(t,f,4094);Log($"Scan VLAN {f}..{t}");var prog=new Progress<int>(x=>VlanProgress.Value=x);foreach(var r in await l2.ScanVlans(a,SrcMac.Text,DstMac.Text,f,t,p,prog))if(r.Received>0)vlans.Add(r);Hist("Scan VLAN",$"{f}-{t}, {vlans.Count} VLAN(s) vus");Log("Scan VLAN terminé.");}catch(Exception ex){Log("Scan VLAN: "+ex.Message);}}
 async void Rfc_Click(object s,RoutedEventArgs e){if(!Guard())return;rfc.Clear();try{double rate=double.Parse(RfcRate.Text);var sz=RfcSizes.Text.Split(',',StringSplitOptions.RemoveEmptyEntries).Select(x=>int.Parse(x.Trim())).Where(x=>x>=64&&x<=9000).ToArray();var prog=new Progress<string>(Log);var svc=new Rfc2544Service(ip);foreach(var x in await svc.Run(Host,Port,rate,sz,prog))rfc.Add(x);var status=rfc.All(x=>x.Status=="PASS")?"PASS":"FAIL";Hist("RFC 2544",$"{rfc.Count} tailles",status);Log("RFC 2544 terminé: "+status);}catch(Exception ex){Log("RFC 2544: "+ex.Message);}}
 void AddService_Click(object s,RoutedEventArgs e){try{yservices.Add(new(YName.Text,int.Parse(YVlan.Text),int.Parse(YPcp.Text),double.Parse(YCir.Text),double.Parse(YEir.Text),double.Parse(YFtd.Text),double.Parse(YFdv.Text),double.Parse(YFlr.Text)));Log("Service Y.1564 ajouté: "+YName.Text);}catch(Exception ex){Log("Profil Y.1564: "+ex.Message);}}
 async Task RunY(bool perf){if(!Guard())return;if(yservices.Count==0)AddService_Click(this,new RoutedEventArgs());yresults.Clear();try{var svc=new Y1564TestService(ip);var dur=TimeSpan.FromSeconds(double.TryParse(YDuration.Text,out var d)?Math.Max(5,d):60);var prog=new Progress<string>(Log);foreach(var x in await svc.Run(Host,Port,yservices,perf,dur,prog))yresults.Add(x);var st=yresults.All(x=>x.Status=="PASS")?"PASS":"FAIL";Hist("Y.1564 "+(perf?"Performance":"Configuration"),$"{yresults.Count} mesures",st);Log("Y.1564 terminé: "+st);}catch(Exception ex){Log("Y.1564: "+ex.Message);}}
 async void YConfig_Click(object s,RoutedEventArgs e)=>await RunY(false); async void YPerf_Click(object s,RoutedEventArgs e)=>await RunY(true);
 void ExportRfc_Click(object s,RoutedEventArgs e){var p=report.ExportCsv(rfc,OutDir,"RFC2544");Log("Export: "+p);} void ExportY_Click(object s,RoutedEventArgs e){var p=report.ExportCsv(yresults,OutDir,"Y1564");Log("Export: "+p);} void ExportHistory_Click(object s,RoutedEventArgs e){var p=report.ExportJson(history,OutDir,"Historique");Log("Export: "+p);} void ClearLog_Click(object s,RoutedEventArgs e)=>LogBox.Clear();
 protected override void OnClosed(EventArgs e){rx.Stop();l2.Dispose();base.OnClosed(e);}
}
